language: ruby
rvm:
  - "1.9.3"
gemfile:
  - Gemfile
services:
  - redis-server
before_script:
  - mkdir -p ./log
  - git submodule --quiet update --init
script: bundle exec rspec spec && bundle exec cucumber features
