language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
env:
  - ENTITIES=10 INTERVAL=120
gemfile:
  - Gemfile
services:
  - redis-server
before_script:
  - mkdir -p ./log
before_install:
  - git submodule update --init --recursive
  - gem install bundler
script: bundle exec rspec spec && bundle exec cucumber features
